// Constants
export const SET_MEASUREMENTS = 'SET_MEASUREMENTS';
export const UPDATE_HEARTBEAT = 'UPDATE_HEARTBEAT';
export const SET_NEW_MEASURE = 'SET_NEW_MEASURE';
export const SET_LOADING = 'SET_LOADING_ON';
